# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"
  - "3.4"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
 - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install -r requirements/test_26.txt; fi
 - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install -r requirements/test_27.txt; fi
 - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pip install -r requirements/test_27.txt; fi
 - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip install -r requirements/test_33.txt; fi
 - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then pip install -r requirements/test_34.txt; fi

# command to run tests, e.g. python setup.py test
script: python setup.py test
